# Generated by Django 5.0.4 on 2024-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
